version: '2'
services:
  samba:
    container_name: samba
    image: dcoon/samba
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      - /mnt/library:/share
      - /home/dcoon/projects/nas/samba/smb.conf:/etc/smb.conf
    restart: always
    command: smbd -FS
