version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ALLOWED_NETWORKS=10.1.0.0/16
      - PLEX_CLAIM=claim-1_zabsecNbzuwAKUcWL1
    volumes:
      - /mnt/library/Plex/config:/config
      - /mnt/library/Plex/transcode:/transcode
      - /mnt/library:/library
    restart: unless-stopped
