version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #      - UMASK_SET=022 #optional
    volumes:
      - /Users/dcoon/temp/radarr/config:/config
      - /Volumes/library/Videos/Movies-inbox:/movies
      - /Volumes/library/Torrent2:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - /Users/dcoon/temp/transmission/config:/config
      - /Volumes/library/Torrent2:/downloads
      - /Volumes/library/Torrent2/Inbox:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #- RUN_OPTS=run options here #optional
    volumes:
      - /Users/dcoon/temp/jackett/config:/config
      - /Volumes/library/Torrent2:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #- UMASK_SET=022 #optional
    volumes:
      - /Users/dcoon/temp/sonarr/config:/config
      - /Volumes/library/Videos/TV:/tv
      - /Volumes/library/Torrent2:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
        #- UMASK_SET=022 #optional
    volumes:
      - /Users/dcoon/temp/lidarr/config:/config
      - /Volumes/library/Music/Music-inbox:/music
      - /Volumes/library/Torrent2:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
