# java.docker
#
# VERSION               0.0.1

FROM      ubuntu
MAINTAINER David Coon "dcoon@davidcoon.org"

# make sure the package repository is up to date
RUN apt-get update && apt-get clean 

# install java
RUN apt-get install -y openjdk-7-jre 

